name = "Overly Orange"
license = "MIT"
licenselink = "https://github.com/johnnymatthews/overly-orange/blob/main/LICENSE"
description = "An orange-inspired theme. Like, it's inspired by the colour orange, not the fruit. Although, I guess it could be both."
homepage = "http://johnnymatthews.dev/"
tags = ["monospace", "blog", "simple", "fast", "orange", "dark", "light"]
min_version = "0.41"

[author]
  name = "Johnny Matthews"
  homepage = "johnnymatthews.dev"
